name: Maven Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/upload-artifact@v2
      with:
        name: aip-console-tools-cli.jar
        path: aip-console-tools-cli/target/aip-console-tools-cli.jar
    - uses: actions/upload-artifact@v2
      with:
        name: aip-console-jenkins.hpi
        path: aip-console-jenkins/target/aip-console-jenkins.hpi

